### ISSUE TITLE
默认使用全局过期时间，报错

### ISSUE THREAD

**Issue by xiaomingfor** [pig-mesh/multilevel-cache-spring-boot-starter#14]
private void doPut(Object key, Object value) {
		Duration expire = getExpire();
		value = toStoreValue(value);
		if (!expire.isNegative()) {
			stringKeyRedisTemplate.opsForValue().set(getKey(key), value, expire);
		}
		else {
			stringKeyRedisTemplate.opsForValue().set(getKey(key), value);
		}

		push(new CacheMessage(this.name, key));

		caffeineCache.put(key, value);
	}

在doPut方法中，默认不设置时间则采用全局过期时间，全局过期时间设置为0，默认不过期，但在这里走的是stringKeyRedisTemplate.opsForValue().set(getKey(key), value, expire);这条语句，导致报错。

**Comment by lltx** [comment]
fix
