### ISSUE TITLE
建议添加根据key前缀删除缓存

### ISSUE THREAD

**Issue by graham-lemon** [pig-mesh/multilevel-cache-spring-boot-starter#4]
- 缓存名称：cacheName:key1-key2-key3
- 例子：查询多条集合数据、与更新一条数据
  - 根据`cacheName:key1-key2-key3`（id-类型-数量）返回集合数据
  - 根据`cacheName:key1-key2`（id-类型）更新一条数据
- 建议添加更新完一条数据后，设置所有缓存key前缀为`cacheName:key1-key2`的缓存数据失效功能

**Comment by lltx** [comment]
这个需求 和 spring cache 就有些不兼容了


--

spring cache 默认提供一个 是一个指定key 一个是全部
